# Generated by Django 5.2.4 on 2025-07-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
